services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pashto-backend-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pashto-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
