version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.mjs:/app/vite.config.mjs
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
